<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_placaAgente</name>
   <tag></tag>
   <elementGuidId>8bb0accb-71d1-4ed6-a3bc-5e086abe88d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'content:fomrbuscarAgen:textPlacaAgente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fca7863-274b-4e6d-85db-c58538985375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content:fomrbuscarAgen:textPlacaAgente</value>
      <webElementGuid>7e2b2fa0-2f3d-44ee-b747-13dc9cea4861</webElementGuid>
   </webElementProperties>
</WebElementEntity>
