<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_concesionario</name>
   <tag></tag>
   <elementGuidId>396b51f9-98bf-4676-8665-464c7cd7ae7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id=&quot;formAdmonTalonarios:selectConcesion&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8a9ce6d0-9cb0-491e-8219-417affc042c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id=&quot;formAdmonTalonarios:selectConcesion&quot;]</value>
      <webElementGuid>116b01af-9b69-4974-8f9b-0da9c23e67a8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
