<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_placaAgente</name>
   <tag></tag>
   <elementGuidId>53607f16-a6cf-4d8b-8dc5-73c06766fa1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;formAdmonTalonarios:textPlacaAgente&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07cfd47d-1d0c-46c1-8dbf-bd568641ccdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;formAdmonTalonarios:textPlacaAgente&quot;]</value>
      <webElementGuid>82079e06-7dac-4899-9885-dbfe44189211</webElementGuid>
   </webElementProperties>
</WebElementEntity>
