<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nroInicialRango</name>
   <tag></tag>
   <elementGuidId>2ba78b84-2677-4b83-ac3a-155af3ffa35f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;formAdmonTalonarios:textNroRangoInicial&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04910609-e8c0-4fab-9174-447a1e08ad20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;formAdmonTalonarios:textNroRangoInicial&quot;]</value>
      <webElementGuid>74185a5a-37c1-40d0-8e5c-c4ea8517bf2b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
