<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nroFinalRango</name>
   <tag></tag>
   <elementGuidId>a81d98e4-9eb2-4ce3-af61-487106ffbf8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;formAdmonTalonarios:textNroRangoFinal&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>200e283e-2801-468c-b4dd-c703b3539790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;formAdmonTalonarios:textNroRangoFinal&quot;]</value>
      <webElementGuid>a30c0f84-f6bc-4609-8e16-1838ec6d3499</webElementGuid>
   </webElementProperties>
</WebElementEntity>
