<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_tipoTalonario</name>
   <tag></tag>
   <elementGuidId>6261ae71-ad7a-4ed9-abe7-8dc60c90ee80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id=&quot;formAdmonTalonarios:selectTipoTalonarioForm&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d664ae07-a67d-4f27-9ca2-b35b1bc340ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id=&quot;formAdmonTalonarios:selectTipoTalonarioForm&quot;]</value>
      <webElementGuid>89d2655f-c821-4077-b5d2-829a3d8be9bc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
