<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_verMasOpciones</name>
   <tag></tag>
   <elementGuidId>063b73d2-c6d5-416d-9375-de0b82758938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'j_idt363:j_idt425']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb92f8d9-4f65-4afe-81f7-b542011be4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt363:j_idt425</value>
      <webElementGuid>71dfce27-7787-4fe4-9094-1db78a3461f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
