<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_guardarActualizacion</name>
   <tag></tag>
   <elementGuidId>59befe35-17e1-4de3-b49a-940fdc1e5a22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'popupPopupActualizar:j_idt430']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f175fda1-fd8f-4da7-bbff-c079c935e6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupPopupActualizar:j_idt430</value>
      <webElementGuid>5caaaac0-99ef-4080-b401-8f301998aa2d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
