<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_buscar</name>
   <tag></tag>
   <elementGuidId>b38f6f1a-b253-415a-b11a-965828f40428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'content:j_idt388']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6177e0ed-028c-4b84-8f39-04fa00979805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content:j_idt388</value>
      <webElementGuid>c45bba36-3ca4-482b-82ed-e7808c394d07</webElementGuid>
   </webElementProperties>
</WebElementEntity>
