<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_generarArchivoParaEnvioOT</name>
   <tag></tag>
   <elementGuidId>4e4ccb6e-e5e2-455c-bfc7-fe86eab88229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id=&quot;j_idt363:j_idt421&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f07f1120-8c62-43f8-97ef-9b304bb8b307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id=&quot;j_idt363:j_idt421&quot;]</value>
      <webElementGuid>529ef38c-3142-4dc5-a3d4-cbaecf2a1c35</webElementGuid>
   </webElementProperties>
</WebElementEntity>
