<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_generar</name>
   <tag></tag>
   <elementGuidId>1ed2fba4-b5d9-44c4-9b93-a004f6d57e42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id=&quot;content:j_idt379&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6cf5e9cb-7df5-4012-8567-ee691a6906e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id=&quot;content:j_idt379&quot;]</value>
      <webElementGuid>7c637189-ebe0-4c16-8861-ebdd8572ae4f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
