<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_tipoComparendo</name>
   <tag></tag>
   <elementGuidId>bdd03e4c-f8e8-4aeb-bf01-57e964843193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id=&quot;content:selectTipoComparendo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c14fec29-5b01-4c72-b8d0-9bfdd0b409aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id=&quot;content:selectTipoComparendo&quot;]</value>
      <webElementGuid>b8a955a1-2640-438d-a85c-e03ef9bcc681</webElementGuid>
   </webElementProperties>
</WebElementEntity>
