<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_secretaria</name>
   <tag></tag>
   <elementGuidId>d3f16d61-0493-41e0-81ee-f62d70e922db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id=&quot;content:selectSecretaria&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dfbee574-e7f3-412a-92ea-2232ebe95ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id=&quot;content:selectSecretaria&quot;]</value>
      <webElementGuid>85253a82-ae62-4cc7-a611-f63e40aa12ed</webElementGuid>
   </webElementProperties>
</WebElementEntity>
