<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bnt_buscarAgente</name>
   <tag></tag>
   <elementGuidId>3579a101-f425-4546-b077-08019b7e1832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'formContent:j_idt382']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5fdbf87-5195-4b26-b5a6-7be222dc4d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formContent:j_idt382</value>
      <webElementGuid>805d0a51-0f2e-4535-9df2-89dd0f147df5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
