<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_guardarEdicion</name>
   <tag></tag>
   <elementGuidId>8955adb1-bb45-4716-9d87-5aa569c188b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'formContent:j_idt447']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b2048a3-704e-44a8-b15d-34efc6673f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formContent:j_idt447</value>
      <webElementGuid>32667fd9-1b65-4544-b260-d294b85e5aa2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
