<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_verificaEdicionGrabada</name>
   <tag></tag>
   <elementGuidId>f466f69d-626a-4dd8-b91e-8e3922edee78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'j_idt350']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff26de43-1184-43fb-8357-84df4290e98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt350</value>
      <webElementGuid>76d049f6-599f-41dc-b4b9-28f13cc7e625</webElementGuid>
   </webElementProperties>
</WebElementEntity>
