<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_verificacionTitulo</name>
   <tag></tag>
   <elementGuidId>38e08b2b-48e2-4ff4-bc83-0d80833f8c56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'j_idt206:j_idt207:0:j_idt208']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>012ef9a1-4f67-477f-9ddf-86d330b649a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt206:j_idt207:0:j_idt208</value>
      <webElementGuid>c03bf2a8-a959-4797-a659-6314dbab5e86</webElementGuid>
   </webElementProperties>
</WebElementEntity>
