<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_menuGenerarArchivoPlanoComparendo</name>
   <tag></tag>
   <elementGuidId>95811af2-0694-46f7-84cc-942c75590abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='j_idt363:j_idt422']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d32e641b-cc5c-4618-b238-40f15f45bae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt363:j_idt422</value>
      <webElementGuid>10ff1467-232b-4915-b017-77782491f13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9d4b2787-a107-457a-9478-25a6db656cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink linkMenu</value>
      <webElementGuid>234b1c1d-627b-43e3-87ed-3818b187ba3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({source:'j_idt363:j_idt422'});return false;</value>
      <webElementGuid>ed654752-10a0-4601-acb3-3aa8baf5a418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Generar archivo plano comparendos</value>
      <webElementGuid>9a78eb54-e361-449e-9e9f-a04ca041286b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt363:j_idt422&quot;)</value>
      <webElementGuid>37691689-655e-42c9-869e-b701467ac17e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='j_idt363:j_idt422']</value>
      <webElementGuid>21eb02c3-d56a-4c38-b7d3-b1d646f97b27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
