<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_tipoComparendo</name>
   <tag></tag>
   <elementGuidId>df0d30fd-a5c0-420c-bd13-59420ea5a07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='content:selectTipoComparendo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>419359e3-ccb0-4e48-a0ff-5fe6e13025ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content:selectTipoComparendo</value>
      <webElementGuid>1ad75cc1-d059-4bf4-aaee-d133a6f829da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content:selectTipoComparendo</value>
      <webElementGuid>5f60fa5f-7eb9-4f22-85c3-d6c6c985c6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>990d3e8e-0e7f-4739-ae6b-a83402cb7ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b3e84b7e-993a-46c9-89ad-21f309acd3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({source:this,event:'change',process:'content:selectTipoComparendo'}, arguments[1]);</value>
      <webElementGuid>818bf26c-d8b9-4088-bf24-1bcffec54d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	
	Transito
	Transporte
</value>
      <webElementGuid>8a2b27ea-0c2b-43c4-aba1-6be666420ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content:selectTipoComparendo&quot;)</value>
      <webElementGuid>1bdca625-4def-4726-85bb-cbf7d5fc510d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='content:selectTipoComparendo']</value>
      <webElementGuid>ab871fa5-afbc-480f-b5eb-007660aeda38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='content']/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>15229e05-ecf2-4298-a1cb-d1fe37f4f7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>4ebee386-7d07-41c4-9032-a6d6da313406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
