<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_verificacionRegistroC</name>
   <tag></tag>
   <elementGuidId>3e04c1e1-9299-4274-a54f-14902037b3da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'ui-messages-warn-summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-messages-warn-summary</value>
      <webElementGuid>a4d7dbcf-8d77-4d84-bc8f-b49b8033fdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd609322-eb93-4e45-926f-b93569b8c097</webElementGuid>
   </webElementProperties>
</WebElementEntity>
