<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_imprimir</name>
   <tag></tag>
   <elementGuidId>41994789-deab-467e-9fe8-bd59085c0237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id=&quot;formAdmonTalonarios:j_idt407&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c28a8655-e8f8-43ef-b9cd-ade7b583e7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id=&quot;formAdmonTalonarios:j_idt407&quot;]</value>
      <webElementGuid>2fc1e521-42d4-488c-a59b-75bca91be105</webElementGuid>
   </webElementProperties>
</WebElementEntity>
