<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_buscar</name>
   <tag></tag>
   <elementGuidId>924a2f09-14bb-4d24-8188-0a109eb0e56e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'content:j_idt375']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content:j_idt375</value>
      <webElementGuid>47b6e82b-e366-4e8a-932f-03d59a77a71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e3927d0-f9bf-4d75-9e9f-e98497a6daef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
