<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_secretaria</name>
   <tag></tag>
   <elementGuidId>c5c929c1-5f53-4bfb-aff7-7d3fe0dded0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'content:selectSecretaria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content:selectSecretaria</value>
      <webElementGuid>0c47302a-6c7a-4d58-bc8e-d190f14cd645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>507b3bc6-1a73-4f06-a550-9a34a2c11956</webElementGuid>
   </webElementProperties>
</WebElementEntity>
