<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_criterioBusqueda</name>
   <tag></tag>
   <elementGuidId>87e4e99e-893c-452b-ac46-84176097ca40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'formContent:criterio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>56c532a6-5846-47be-8752-2da891332929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formContent:criterio</value>
      <webElementGuid>57ab16f3-9d22-4feb-9a1f-0fcbad366dd5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
