<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_verificacionTitulo</name>
   <tag></tag>
   <elementGuidId>994a86c2-c5e2-4c06-865c-1b60a932cd11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'j_idt206:j_idt207:0:j_idt208']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>387255d3-e1bb-4cdf-b228-9fc17eaadc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt206:j_idt207:0:j_idt208</value>
      <webElementGuid>86d5a4e9-290d-41d4-a6cb-af7aa1bbb424</webElementGuid>
   </webElementProperties>
</WebElementEntity>
