<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_motivoInactivacion</name>
   <tag></tag>
   <elementGuidId>54c99f4a-2cbb-46b5-9c4b-29882ec5ac76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id=&quot;inactivationForm:textObservacion&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d8995098-859a-4f26-8c35-611f9aeed9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id=&quot;inactivationForm:textObservacion&quot;]</value>
      <webElementGuid>674cd529-ed8a-446c-a981-adadf307b44f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
