<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_adicionarAgente</name>
   <tag></tag>
   <elementGuidId>b25e8acd-e3eb-48b2-9ba6-0f6d90195193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'formContent:j_idt391']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>836df809-9a1e-43ba-8b25-4d5914a5bc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formContent:j_idt391</value>
      <webElementGuid>96e0776d-9f74-4c8b-a562-43f23bec87ac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
