<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_usuario</name>
   <tag></tag>
   <elementGuidId>3ba68335-8f1b-4054-bd5a-35cb33b62b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'formContent:textUsuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c49b71f-4b0d-4950-b689-844f477f75ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formContent:textUsuario</value>
      <webElementGuid>910147b1-2c8b-4505-a5a9-48eba0558e77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
