<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_verificacionTitulo</name>
   <tag></tag>
   <elementGuidId>8e44f3bb-322a-4736-b2dd-0998e20dfbff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'j_idt206:j_idt207:0:j_idt208']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0e004414-fdc0-49ce-a6f6-37035c8be26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt206:j_idt207:0:j_idt208</value>
      <webElementGuid>95e3f745-2b3b-4088-b471-8b941ab11646</webElementGuid>
   </webElementProperties>
</WebElementEntity>
