<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_siEliminarTalonario</name>
   <tag></tag>
   <elementGuidId>887a57a4-01c9-466d-becb-db70b53f6c08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id=&quot;formAdmonTalonarios:j_idt483&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7018391-eff5-43a7-90b1-7059ffb41ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id=&quot;formAdmonTalonarios:j_idt483&quot;]</value>
      <webElementGuid>b4799097-a1e7-4e37-8601-6801fe2003b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
